[package]
name = "vi-brady-recon"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
handlebars = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
vi-ledger = { path = "../vi-ledger" }
