//! JIT LASM — laws uit/pleading assembly engine (evidence-package stage).
//! Phase 4 scope: renders a substantiated-flag evidence bundle (flag ledger
//! hashes included for tamper-evidence) as attorney-review Markdown → PDF and
//! e-filing integration come later. Output is work product for counsel, never
//! filed unreviewed (UPL guardrail).
#![forbid(unsafe_code)]

use handlebars::Handlebars;
use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct FlagSummary {
    pub label: String,
    pub severity: String,
    pub matched: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct LedgerRef {
    pub seq: i64,
    pub event_type: String,
    pub entry_hash: String,
}

#[derive(Debug, Serialize)]
pub struct EvidencePackage<'a> {
    pub caption: &'a str,
    pub docket_number: &'a str,
    pub flags: Vec<FlagSummary>,
    pub ledger: Vec<LedgerRef>,
}

const TEMPLATE: &str = r#"# Evidence Package — Attorney Work Product
**Matter:** {{caption}} ({{docket_number}})
**Generated by VisionInjustice. Requires licensed-attorney review before any use.**

## Substantiated Findings
{{#each flags}}
### {{label}} — severity: {{severity}}
{{#each matched}}- `{{this}}`
{{/each}}
{{/each}}

## Provenance (Root Ledger)
| seq | event | entry hash (BLAKE3) |
|----:|-------|---------------------|
{{#each ledger}}| {{seq}} | {{event_type}} | `{{entry_hash}}` |
{{/each}}

*Chain integrity independently verifiable via GET /ledger/verify.*
"#;

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct RenderError(String);

impl From<handlebars::TemplateError> for RenderError {
    fn from(e: handlebars::TemplateError) -> Self {
        Self(e.to_string())
    }
}
impl From<handlebars::RenderError> for RenderError {
    fn from(e: handlebars::RenderError) -> Self {
        Self(e.to_string())
    }
}

pub fn render(pkg: &EvidencePackage) -> Result<String, RenderError> {
    let mut h = Handlebars::new();
    h.register_template_string("pkg", TEMPLATE)?;
    Ok(h.render("pkg", pkg)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_work_product_banner() {
        let md = render(&EvidencePackage {
            caption: "Demo v. Demo",
            docket_number: "DEMO-2024-001",
            flags: vec![FlagSummary {
                label: "Plea coercion suspected".into(),
                severity: "high".into(),
                matched: vec!["case.plea_sentence_ratio < 0.5".into()],
            }],
            ledger: vec![LedgerRef {
                seq: 1,
                event_type: "AbuseFlag".into(),
                entry_hash: "abc".into(),
            }],
        })
        .unwrap();
        assert!(md.contains("Attorney Work Product"));
        assert!(md.contains("Plea coercion suspected"));
        assert!(md.contains("DEMO-2024-001"));
    }
}
