//! JIT LASM — laws uit/pleading assembly engine (evidence-package stage).
//! Phase 4 scope: renders a substantiated-flag evidence bundle (flag ledger
//! hashes included for tamper-evidence) as attorney-review Markdown → PDF and
//! e-filing integration come later. Output is work product for counsel, never
//! filed unreviewed (UPL guardrail).
#![forbid(unsafe_code)]

use handlebars::Handlebars;
use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct FlagSummary {
    pub label: String,
    pub severity: String,
    pub matched: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct LedgerRef {
    pub seq: i64,
    pub event_type: String,
    pub entry_hash: String,
}

#[derive(Debug, Serialize, Default)]
pub struct BradyGap {
    pub item_type: String,
    pub description: String,
    pub source_reference: String,
}

#[derive(Debug, Serialize, Default)]
pub struct MonellSummary {
    pub office: String,
    pub total_substantiated: i64,
    pub interpretation: String,
}

#[derive(Debug, Serialize, Default)]
pub struct TrialPenaltySummary {
    pub office: String,
    pub n: i64,
    pub mean_ratio: Option<f64>,
}

#[derive(Debug, Serialize)]
pub struct EvidencePackage {
    pub caption: String,
    pub docket_number: String,
    pub flags: Vec<FlagSummary>,
    pub ledger: Vec<LedgerRef>,
    pub brady_gaps: Vec<BradyGap>,
    pub monell: Option<MonellSummary>,
    pub trial_penalty: Option<TrialPenaltySummary>,
}

const TEMPLATE: &str = r#"# Evidence Package — Attorney Work Product
**Matter:** {{caption}} ({{docket_number}})
**Generated by VisionInjustice. Requires licensed-attorney review before any use.**

## Substantiated Findings
{{#each flags}}
### {{label}} — severity: {{severity}}
{{#each matched}}- `{{this}}`
{{/each}}
{{/each}}
{{#unless flags}}_No substantiated TrustScript flags for this matter._
{{/unless}}

## Brady Reconciliation Leads
Gaps below are *research leads*, not proven Brady violations. They require attorney review and a discovery/FOIA record before any filing.
{{#each brady_gaps}}
- **{{item_type}}:** {{description}} (source: {{source_reference}})
{{/each}}
{{#unless brady_gaps}}_No Brady recon gaps on file for this matter. Run POST /brady/reconcile/:case_id first._
{{/unless}}

## Monell / Pattern-and-Practice (office)
{{#if monell}}
**Office:** {{monell.office}} — **substantiated findings:** {{monell.total_substantiated}}

{{monell.interpretation}}
{{else}}
_No office fingerprint available._
{{/if}}

## Trial-Penalty Observatory (office)
{{#if trial_penalty}}
**Office:** {{trial_penalty.office}} — **eligible cases:** {{trial_penalty.n}} — **mean trial/plea ratio:** {{trial_penalty.mean_ratio}}
{{else}}
_No trial-penalty snapshot available._
{{/if}}

## Provenance (Root Ledger)
| seq | event | entry hash (BLAKE3) |
|----:|-------|---------------------|
{{#each ledger}}| {{seq}} | {{event_type}} | `{{entry_hash}}` |
{{/each}}

*Chain integrity independently verifiable via GET /ledger/verify.*
"#;

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct RenderError(String);

impl From<handlebars::TemplateError> for RenderError {
    fn from(e: handlebars::TemplateError) -> Self {
        Self(e.to_string())
    }
}
impl From<handlebars::RenderError> for RenderError {
    fn from(e: handlebars::RenderError) -> Self {
        Self(e.to_string())
    }
}

pub fn render(pkg: &EvidencePackage) -> Result<String, RenderError> {
    let mut h = Handlebars::new();
    h.set_strict_mode(false);
    h.register_template_string("pkg", TEMPLATE)?;
    Ok(h.render("pkg", pkg)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_pkg() -> EvidencePackage {
        EvidencePackage {
            caption: "Demo v. Demo".into(),
            docket_number: "DEMO-2024-001".into(),
            flags: vec![FlagSummary {
                label: "Plea coercion suspected".into(),
                severity: "high".into(),
                matched: vec!["case.plea_sentence_ratio < 0.5".into()],
            }],
            ledger: vec![LedgerRef {
                seq: 1,
                event_type: "AbuseFlag".into(),
                entry_hash: "abc".into(),
            }],
            brady_gaps: vec![BradyGap {
                item_type: "bodycam".into(),
                description: "Body-worn camera footage".into(),
                source_reference: "Demo v. Demo (2024)".into(),
            }],
            monell: Some(MonellSummary {
                office: "Demo County DA".into(),
                total_substantiated: 1,
                interpretation: "Review required.".into(),
            }),
            trial_penalty: Some(TrialPenaltySummary {
                office: "Demo County DA".into(),
                n: 2,
                mean_ratio: Some(2.25),
            }),
        }
    }

    #[test]
    fn renders_work_product_banner() {
        let md = render(&base_pkg()).unwrap();
        assert!(md.contains("Attorney Work Product"));
        assert!(md.contains("Plea coercion suspected"));
        assert!(md.contains("DEMO-2024-001"));
        assert!(md.contains("research leads"));
        assert!(md.contains("Body-worn camera footage"));
        assert!(md.contains("Demo County DA"));
        assert!(md.contains("2.25"));
    }
}
