use crate::stats::Fingerprint;
use handlebars::Handlebars;

const TEMPLATE: &str = r#"# Monell Pattern-and-Practice Assessment — Attorney Work Product
**Office:** {{office}}
**Jurisdiction:** {{jurisdiction}}
**Generated by VisionInjustice. Requires licensed-attorney review before any filing.**

## Executive Summary
{{interpretation}}

## Substantiated Constitutional Findings
| Violation Type | Count | Office Rate (per 1,000) | State Rate (per 1,000) | z-score | p (1-tailed) |
|---------------|-------|-------------------------|------------------------|---------|--------------|
{{#each by_type}}| {{finding_type}} | {{office_count}} | {{office_rate_per_1000}} | {{state_rate_per_1000}} | {{z_score}} | {{p_value_one_tailed}} |
{{/each}}

**Total substantiated findings:** {{total_substantiated}}
**Substantiated findings in last 5 years:** {{recent_5yr}}

## Decision-Maker Clusters
**Judges most frequently finding violations in this office:**
{{#each top_judges}}- {{name}}: {{count}}
{{/each}}

**Individual prosecutors named in substantiated findings:**
{{#each top_prosecutors}}- {{name}}: {{count}}
{{/each}}

## Plausible Monell Theories
1. **Inadequate training / custom** — repeated findings of the same type suggest a systemic failure to train or supervise.
2. **Ratification** — supervisors retained, promoted, or failed to discipline prosecutors after documented violations.
3. **Deliberate indifference** — leadership had notice of the pattern through appellate reversals, sanctions, or civil payouts and failed to reform.

## Next Steps
- Obtain office training manuals, discipline records, and promotion records via FOIA/sunshine.
- Map each finding to a supervisor, training date, and any subsequent corrective action.
- Evaluate civil-rights counsel for §1983 *Monell* litigation.

*Only review_status='substantiated' findings are included. All entries trace to court orders, bar records, or other public documents.*
"#;

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct RenderError(String);

impl From<handlebars::TemplateError> for RenderError {
    fn from(e: handlebars::TemplateError) -> Self {
        Self(e.to_string())
    }
}
impl From<handlebars::RenderError> for RenderError {
    fn from(e: handlebars::RenderError) -> Self {
        Self(e.to_string())
    }
}

pub fn render(fp: &Fingerprint) -> Result<String, RenderError> {
    let mut h = Handlebars::new();
    h.register_template_string("monell", TEMPLATE)?;
    Ok(h.render("monell", fp)?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stats::{Fingerprint, TypeCompare};

    #[test]
    fn banner_and_gate() {
        let md = render(&Fingerprint {
            office: "Demo County DA".into(),
            jurisdiction: Some("CA".into()),
            total_substantiated: 1,
            recent_5yr: 1,
            by_type: vec![TypeCompare {
                finding_type: "brady".into(),
                office_count: 1,
                office_rate_per_1000: 333.0,
                state_rate_per_1000: 0.0,
                z_score: 0.5,
                p_value_one_tailed: 0.3,
            }],
            top_judges: vec![],
            top_prosecutors: vec![],
            interpretation: "test interpretation".into(),
        })
        .unwrap();
        assert!(md.contains("Attorney Work Product"));
        assert!(md.contains("Demo County DA"));
        assert!(md.contains("substantiated"));
    }
}
