//! Markdown work-product renderer for constitution screens.
#![forbid(unsafe_code)]

use handlebars::Handlebars;

use crate::screen::ScreenReport;

const TEMPLATE: &str = r#"# Constitutional Screen — Attorney Work Product
**Jurisdiction:** {{jurisdiction}}{{#if circuit}} ({{circuit}}){{/if}}
**Snapshot:** {{snapshot_id}}
**Corpus hash (BLAKE3):** `{{corpus_hash}}`
**Authority:** {{authority}}

Generated by VisionInjustice. Requires licensed-attorney review before any use. This is **not legal advice**. Hits are research leads, not findings of constitutional violation. The interpretation snapshot is curated and incomplete.

{{#each hits}}
## {{label}} — {{severity}}
**Clause:** `{{clause_id}}` — {{resolution.clause_label}}
**Status:** {{resolution.status}}
{{#if resolution.binding}}
**SCOTUS floor:** {{resolution.binding.citation}} — {{resolution.binding.rule_statement}}
{{/if}}
{{#if resolution.split}}
**Circuit split (unsettled):** {{resolution.split.question}}
- Side A ({{resolution.split.side_a_circuits}}): {{resolution.split.side_a_view}}
- Side B ({{resolution.split.side_b_circuits}}): {{resolution.split.side_b_view}}
{{/if}}
{{#if resolution.state_analog}}
**State analog:** {{resolution.state_analog.state_citation}} ({{resolution.state_analog.relation}}{{#if resolution.state_analog.state_above_federal}}; may raise the federal floor{{/if}})
{{/if}}

Matched facts:
{{#each matched}}- {{this}}
{{/each}}

{{#each resolution.notes}}- {{this}}
{{/each}}
{{/each}}
{{#unless hits}}
_No clause-level leads from the public-record facts supplied._
{{/unless}}

*Only `review_status='substantiated'` materials may be published against named individuals. Automated screens remain pending.*
"#;

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct RenderError(String);

impl From<handlebars::TemplateError> for RenderError {
    fn from(e: handlebars::TemplateError) -> Self {
        Self(e.to_string())
    }
}
impl From<handlebars::RenderError> for RenderError {
    fn from(e: handlebars::RenderError) -> Self {
        Self(e.to_string())
    }
}

pub fn render(report: &ScreenReport) -> Result<String, RenderError> {
    let mut h = Handlebars::new();
    h.set_strict_mode(false);
    h.register_template_string("constitution", TEMPLATE)?;
    Ok(h.render("constitution", report)?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::screen::{screen, ScreenInput};

    #[test]
    fn banner_and_not_legal_advice() {
        let report = screen(&ScreenInput {
            jurisdiction: "CA".into(),
            court_level: Some("superior".into()),
            plea_offered: Some(true),
            plea_accepted: Some(false),
            outcome: Some("conviction".into()),
            plea_offer_months: Some(12),
            sentence_months: Some(36),
            evidence_strength: Some("weak".into()),
            ..Default::default()
        });
        let md = render(&report).unwrap();
        assert!(md.contains("Attorney Work Product"));
        assert!(md.contains("not legal advice"));
        assert!(md.contains("amend.06"));
    }
}
