use crate::distribution::PenaltyDistribution;
use handlebars::Handlebars;
use serde::Serialize;

const TEMPLATE: &str = r#"# DRAFT MOTION / POLICY BRIEF — Trial-Penalty Challenge
**To:** [Court / Legislature / Criminal Rules Committee]
**Re:** Systematic trial-penalty coercion in {{office}}

## Statement of Facts
In {{office}}, defendants who reject the prosecutor's plea offer, exercise their Sixth Amendment right to trial, and are convicted receive sentences that are, on average, {{mean_ratio}} times the last plea offer. The median ratio is {{median_ratio}}; the 90th percentile reaches {{p90_ratio}}. The analysis included {{n}} eligible cases (plea offered, plea rejected, convicted at trial).

## Legal Argument
A plea-bargaining structure that imposes a multiplicative sentencing premium for exercising the right to trial is not a voluntary waiver under *Boykin v. Alabama*, 395 U.S. 238 (1969), but a coerced abandonment of constitutional rights. While *Bordenkircher v. Hayes*, 434 U.S. 357 (1978), permits charging discretion, it does not authorize a systemic practice that functionally punishes the choice to stand trial. When the premium is this large and this consistent, the waiver is no longer knowing and voluntary.

## Requested Relief
- [ ] Declare the office's plea practices unconstitutional as applied to the class of similarly situated defendants.
- [ ] Order production of all plea histories, sentence matrices, and charging memoranda.
- [ ] Adopt judicially supervised plea guidelines that cap the trial-to-plea sentence premium at a constitutionally tolerable ratio.

## Data Provenance
Statistics generated by the VisionInjustice Trial Penalty Observatory from public docket and sentencing records, with a full audit trail in the Root Ledger.

**Draft only — attorney review required before any filing.**
"#;

#[derive(Debug, Serialize)]
pub struct MotionContext {
    pub office: String,
    pub n: i64,
    pub mean_ratio: f64,
    pub median_ratio: f64,
    pub p90_ratio: f64,
}

impl MotionContext {
    pub fn from_distribution(office: String, dist: &PenaltyDistribution) -> Self {
        Self {
            office,
            n: dist.n,
            mean_ratio: dist.mean_ratio.unwrap_or(0.0),
            median_ratio: dist.median_ratio.unwrap_or(0.0),
            p90_ratio: dist.p90_ratio.unwrap_or(0.0),
        }
    }
}

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct RenderError(String);

impl From<handlebars::TemplateError> for RenderError {
    fn from(e: handlebars::TemplateError) -> Self {
        Self(e.to_string())
    }
}
impl From<handlebars::RenderError> for RenderError {
    fn from(e: handlebars::RenderError) -> Self {
        Self(e.to_string())
    }
}

pub fn render(ctx: &MotionContext) -> Result<String, RenderError> {
    let mut h = Handlebars::new();
    h.register_template_string("motion", TEMPLATE)?;
    Ok(h.render("motion", ctx)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn draft_banner() {
        let md = render(&MotionContext {
            office: "Demo County DA".into(),
            n: 2,
            mean_ratio: 2.25,
            median_ratio: 2.25,
            p90_ratio: 3.0,
        })
        .unwrap();
        assert!(md.contains("Draft only"));
        assert!(md.contains("attorney review required"));
        assert!(md.contains("Demo County DA"));
    }
}
