//! Markdown work-product renderers for the Reckoning Engine.
#![forbid(unsafe_code)]

use handlebars::Handlebars;
use serde::Serialize;

use crate::package::PackageContext;

#[derive(Debug, Clone, Serialize)]
pub struct LedgerRef {
    pub seq: i64,
    pub event_type: String,
    pub entry_hash: String,
}

#[derive(Debug, thiserror::Error)]
#[error("{0}")]
pub struct RenderError(String);

impl From<handlebars::TemplateError> for RenderError {
    fn from(e: handlebars::TemplateError) -> Self {
        Self(e.to_string())
    }
}
impl From<handlebars::RenderError> for RenderError {
    fn from(e: handlebars::RenderError) -> Self {
        Self(e.to_string())
    }
}

const PACKAGE_TEMPLATE: &str = r#"# {{title}} — Attorney Work Product
**Subject (Accountability ID):** {{actor.actor_id}}
**Public-record name:** {{actor.display_name}}
**Role:** {{actor.role}}
**Office / jurisdiction:** {{actor.office}} / {{actor.jurisdiction}}
{{#if actor.bar_number}}**Bar number:** {{actor.bar_number}}
{{/if}}{{#if actor.badge_number}}**Badge number:** {{actor.badge_number}}
{{/if}}
Generated by the VisionInjustice Reckoning Engine. This is **not legal advice**, not a charging document, and not a finding of guilt. Licensed counsel must independently verify every element, including mens rea. The subject retains the full due-process rights the system is built to enforce.

## Due Process for the Subject
The engine does not publish pending flags, does not file this package, and does not recommend a sentence. Any later proceeding must prove each element beyond a reasonable doubt (criminal) or by the applicable civil standard. Immunity doctrines are researched below; they are not waived by this document.

## Substantiated Public-Record Evidence
Only `review_status = substantiated` items are included.
{{#each evidence}}
- **{{source_kind}} / {{label}}**{{#if citation}} — {{citation}}{{/if}}{{#if case_id}} (case `{{case_id}}`){{/if}}
  {{summary}}
{{/each}}

## Abuse Score (formula-audited)
**Score:** {{score.score}} / 100
**Formula:** `{{score.formula}}`
**Substantiated findings:** {{score.substantiated_findings}} — **substantiated flags:** {{score.substantiated_flags}} — **corroboration sources:** {{score.corroboration_sources}} — **recent (5y):** {{score.recent_5yr}}

A score is a prioritization signal for counsel. It is not probable cause and not a determination of liability.

## Statute Research (elements, not charges)
{{#each statutes}}
### {{citation}} — {{title}} ({{kind}})
**Elements:**
{{#each elements}}- {{this}}
{{/each}}
**Statutory maximum (research):** {{statutory_maximum}}
**Note:** {{research_note}}
{{/each}}

## Immunity Doctrines (research)
{{#each immunity}}
- **{{doctrine}}** — {{leading_case}}. Scope: {{scope}} Limits: {{recognized_limits}}
{{/each}}

{{#if is_criminal}}
## Referral Destinations (counsel to transmit, if they so advise)
{{#each destinations}}- {{this}}
{{/each}}

Counsel should include: a witness/source index drawn from the public record; the Root Ledger hashes below; and a statement that VisionInjustice is not the complainant of record unless counsel separately appears.
{{/if}}

{{#if is_civil}}
## Civil Rights Scaffold
Plausible theories for counsel to evaluate, not file:
1. **Malicious prosecution / fabrication** under § 1983 where a criminal proceeding terminated in the plaintiff's favor and was procured by fabricated evidence or a Brady/Giglio suppression that shocks the conscience.
2. **Due-process withholding** of material exculpatory evidence.
3. **State torts** (malicious prosecution, IIED) where immunity does not bar them.
4. **Monell** pattern-and-practice against the office (see `/atlas/offices/monell-report`).

Recommended resolution terms *if* counsel settles (policy checklist, not a demand): public admission or stipulated facts; no confidentiality clause that hides the official act; referral of any criminal evidence to the appropriate prosecutor; and expungement or sealing relief for the victim where available. Counsel decides; the engine does not settle cases.
{{/if}}

{{#if is_bar}}
## Bar Complaint Draft
This draft asks the disciplinary authority to investigate. It does not seek a predetermined sanction. Attach the substantiated findings, the ledger hashes, and any court order. Disbarment is a possible outcome of the bar's own process — not a sentence this engine imposes.
{{#each destinations}}- File with: {{this}}
{{/each}}
{{/if}}

{{#if is_sentencing}}
## Statutory Range Research (not a requested sentence)
This memorandum lists statutory maxima that a court could lawfully consider *after* a conviction of the official. The engine does **not** advocate for a maximum, for life imprisonment, or for any particular sentence. Comparable charging decisions by the subject's own office may be relevant mitigation or aggravation; they do not authorize extra-legal punishment.

If no criminal conviction of the official exists, this annex is research only and must not be filed as a sentencing memorandum.
{{/if}}

## Provenance (Root Ledger)
| seq | event | entry hash (BLAKE3) |
|----:|-------|---------------------|
{{#each ledger}}| {{seq}} | {{event_type}} | `{{entry_hash}}` |
{{/each}}

*Chain integrity independently verifiable via GET /ledger/verify.*
"#;

#[derive(Serialize)]
struct PackageView {
    title: String,
    actor: crate::entity::Actor,
    score: crate::score::AbuseScore,
    evidence: Vec<crate::package::EvidenceRow>,
    statutes: Vec<&'static crate::statutes::Statute>,
    immunity: &'static [crate::statutes::ImmunityNote],
    destinations: Vec<&'static str>,
    ledger: Vec<LedgerRef>,
    is_criminal: bool,
    is_civil: bool,
    is_bar: bool,
    is_sentencing: bool,
}

pub fn render_package(ctx: &PackageContext) -> Result<String, RenderError> {
    let title = match ctx.action_kind.as_str() {
        "criminal_referral" => "Criminal Referral Package",
        "civil_1983" => "Civil Rights Lawsuit Scaffold",
        "bar_complaint" => "Bar Disciplinary Complaint Draft",
        "sentencing_memo" => "Statutory Range Research Memorandum",
        other => other,
    };
    let view = PackageView {
        title: title.to_string(),
        actor: ctx.actor.clone(),
        score: ctx.score.clone(),
        evidence: ctx.evidence.clone(),
        statutes: ctx.statutes.clone(),
        immunity: ctx.immunity,
        destinations: ctx.destinations.clone(),
        ledger: ctx.ledger.clone(),
        is_criminal: ctx.action_kind == "criminal_referral",
        is_civil: ctx.action_kind == "civil_1983",
        is_bar: ctx.action_kind == "bar_complaint",
        is_sentencing: ctx.action_kind == "sentencing_memo",
    };
    let mut h = Handlebars::new();
    h.set_strict_mode(false);
    h.register_template_string("pkg", PACKAGE_TEMPLATE)?;
    Ok(h.render("pkg", &view)?)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::Actor;
    use crate::package::{EvidenceRow, PackageContext};
    use crate::score::{AbuseScore, FORMULA};
    use crate::statutes;
    use serde_json::json;
    use uuid::Uuid;

    fn demo_ctx(kind: &str) -> PackageContext {
        PackageContext {
            actor: Actor {
                actor_id: Uuid::nil(),
                role: "prosecutor".into(),
                display_name: "Demo Prosecutor".into(),
                normalized_name: "demo prosecutor".into(),
                office: Some("Demo County DA".into()),
                jurisdiction: "CA".into(),
                bar_number: Some("CA-100001".into()),
                badge_number: None,
                prosecutor_id: None,
                fingerprint: "x".into(),
            },
            score: AbuseScore {
                actor_id: Uuid::nil(),
                score: 28.0,
                substantiated_findings: 1,
                substantiated_flags: 0,
                corroboration_sources: 1,
                recent_5yr: 1,
                formula: FORMULA,
                components: json!({}),
                snapshot_id: None,
            },
            action_kind: kind.into(),
            evidence: vec![EvidenceRow {
                source_kind: "constitutional_finding".into(),
                label: "brady".into(),
                citation: Some("Demo v. Demo (2024)".into()),
                summary: "Opinion notes missing chain of custody.".into(),
                case_id: None,
            }],
            statutes: statutes::for_finding_types(&["brady".into()]),
            immunity: statutes::IMMUNITY,
            destinations: vec!["State Attorney General (criminal division)"],
            ledger: vec![LedgerRef {
                seq: 1,
                event_type: "AbuseScoreComputed".into(),
                entry_hash: "abc".into(),
            }],
        }
    }

    #[test]
    fn criminal_referral_is_work_product_not_a_charge() {
        let md = render_package(&demo_ctx("criminal_referral")).unwrap();
        assert!(md.contains("Attorney Work Product"));
        assert!(md.contains("not a charging document"));
        assert!(md.contains("due-process"));
        assert!(md.contains("18 U.S.C."));
        assert!(md.contains("Demo Prosecutor"));
        assert!(!md.to_lowercase().contains("no mercy"));
        assert!(!md.to_lowercase().contains("life for life"));
    }

    #[test]
    fn sentencing_memo_does_not_request_a_sentence() {
        let md = render_package(&demo_ctx("sentencing_memo")).unwrap();
        assert!(md.contains("does **not** advocate for a maximum"));
        assert!(md.contains("Statutory Range Research"));
    }
}
